// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteDBEntity;

#nullable disable

namespace SQLiteDBEntity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240222155531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("SQLiteDBEntity.Entities.Master.m_sex", b =>
                {
                    b.Property<int>("m_sex_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("create_program")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("create_user")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("m_sex_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("update_program")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("m_sex_id")
                        .HasName("m_sex_PKC");

                    b.ToTable("m_sex");
                });

            modelBuilder.Entity("SQLiteDBEntity.Entities.System.s_master_edit_password", b =>
                {
                    b.Property<int>("system_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("create_program")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("create_user")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("update_program")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("update_user")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("system_id")
                        .HasName("s_master_edit_password_PKC");

                    b.ToTable("s_master_edit_password");
                });
#pragma warning restore 612, 618
        }
    }
}
